
spring:
  datasource:
    url: jdbc:h2:mem:sportsbookdb;MODE=LEGACY
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    defer-datasource-initialization: true